-- Category interest analytics for AXORIA storefront.
-- Stores anonymous category interactions only; no customer PII is collected.

create table if not exists public.category_views (
  id bigint generated by default as identity primary key,
  category text not null,
  session_id uuid not null,
  created_at timestamptz not null default now(),
  constraint category_views_category_length check (char_length(category) between 1 and 100)
);

create index if not exists category_views_category_created_idx
  on public.category_views (category, created_at desc);
create index if not exists category_views_session_idx
  on public.category_views (session_id);

alter table public.category_views enable row level security;

revoke all on table public.category_views from anon, authenticated;
grant insert on table public.category_views to anon, authenticated;
grant select on table public.category_views to authenticated;
grant usage, select on sequence public.category_views_id_seq to anon, authenticated;

drop policy if exists category_views_insert_public on public.category_views;
create policy category_views_insert_public
  on public.category_views
  for insert
  to anon, authenticated
  with check (char_length(category) between 1 and 100 and session_id is not null);

drop policy if exists category_views_read_admin on public.category_views;
create policy category_views_read_admin
  on public.category_views
  for select
  to authenticated
  using (true);
